# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home

#RUN mkdir -p $DAGSTER_HOME
RUN mkdir -p /opt/dagster/app
COPY workspace.yaml dagster.yaml /opt/dagster/app
WORKDIR /opt/dagster/app

COPY repo.py /opt/dagster/app

